name: QALMA (ubuntu) Qutip 5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      run: |
        sudo apt-get update -qq && sudo apt-get install -qq gfortran
    - name: Install QALMA with full dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools  # Add this line
        pip install qutip==5.1
        pip install pytest
        pip install -e .
    - name: Test QALMA
      run: |
        QALMA_ALLTESTS=1 python -m pytest test
